name: Download Latest Compile.exe

on:
  push:
    branches: [ main, master ]

jobs:
  download-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest release info
      id: get_release
      run: |
        # Get the latest release info from sslc repository
        RELEASE_INFO=$(curl -s https://api.github.com/repos/sfall-team/sslc/releases/latest)
        RELEASE_TAG=$(echo "$RELEASE_INFO" | jq -r '.tag_name')
        RELEASE_URL=$(echo "$RELEASE_INFO" | jq -r '.html_url')

        echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT
        echo "Latest release: $RELEASE_TAG"
        echo "Release URL: $RELEASE_URL"

        - name: Find compile.exe asset
      id: find_asset
      run: |
        # Get the latest release info and find compile.exe
        RELEASE_INFO=$(curl -s https://api.github.com/repos/sfall-team/sslc/releases/latest)

        # Check if release exists and has assets
        if [ "$(echo "$RELEASE_INFO" | jq -r '.message')" = "Not Found" ]; then
          echo "Repository or release not found"
          exit 1
        fi

        if [ "$(echo "$RELEASE_INFO" | jq -r '.assets')" = "null" ]; then
          echo "No assets found in latest release"
          exit 1
        fi

        COMPILE_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | contains("compile.exe")) | .browser_download_url' | head -1)
        COMPILE_NAME=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | contains("compile.exe")) | .name' | head -1)

        if [ "$COMPILE_URL" != "null" ] && [ -n "$COMPILE_URL" ]; then
          echo "compile_url=$COMPILE_URL" >> $GITHUB_OUTPUT
          echo "compile_name=$COMPILE_NAME" >> $GITHUB_OUTPUT
          echo "Found compile.exe: $COMPILE_NAME"
          echo "Download URL: $COMPILE_URL"
        else
          echo "No compile.exe found in latest release"
          exit 1
        fi

    - name: Download compile.exe
      run: |
        mkdir -p ./bin
        echo "Downloading compile.exe from: ${{ steps.find_asset.outputs.compile_url }}"
        curl -L -o ./bin/compile.exe "${{ steps.find_asset.outputs.compile_url }}"
        ls -la ./bin/compile.exe
